### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jkw-statsig**
Add row for quick experiments

### CODE REVIEW

**Review by roim — APPROVED** [review]

**Comment by greko6** [comment]
We already have statsig! Thanks! :-)

**Comment by jkw-statsig** [comment]
@greko6 this change is adding a row for people looking for tools like Quick Experiments at Facebook, which the repo does not have yet. I'm actually surprised there isn't a row for QE yet, it's such a big tool at FB.

**Comment by greko6** [comment]
There is a deltoid row. Isn't that the same? 

btw, you're building a really solid tool! :)

**Comment by jkw-statsig** [comment]
Thanks @greko6! We loved these tools at FB and would love to make them available to all!

Deltoid and QE are very different products - QE is used to set up/configure A/B/n experiments, while Deltoid helps with analytics, in addition Deltoid provides features for teams to monitor their team's/org's overall metrics. They are paired great at FB, but usually offered as different products, e.g. you can do experiment analysis by running SQL or using other analytics tools without Deltoid :).

**Pull request closed without merging**
